# Generated by Django 6.0.1 on 2026-01-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The amount charged. Should match the amount on the flower plan.",
                max_digits=10,
            ),
        ),
    ]
