# Generated by Django 6.0.1 on 2026-01-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "hex_code",
                    models.CharField(
                        blank=True, help_text="e.g., #FFFFFF", max_length=7
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        help_text="The date the flower delivery will occur."
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Custom message for this specific delivery.",
                        null=True,
                    ),
                ),
                (
                    "bouquet_preference",
                    models.CharField(
                        blank=True,
                        help_text="User's preference for the bouquet (e.g., 'Sunflowers').",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        help_text="The status of the delivery.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["delivery_date"],
            },
        ),
        migrations.CreateModel(
            name="FlowerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FlowerPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the plan is active. Activated upon successful payment.",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="The date of the first delivery.",
                        null=True,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The budget per bouquet.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "deliveries_per_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How many deliveries are scheduled per year.",
                        null=True,
                    ),
                ),
                (
                    "years",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The total number of years for the plan.",
                        null=True,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The final total amount for the plan.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="The three-letter ISO currency code.",
                        max_length=3,
                    ),
                ),
                (
                    "recipient_first_name",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's first name.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "hash_recipient_first_name",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                (
                    "recipient_last_name",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's last name.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "hash_recipient_last_name",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                (
                    "recipient_street_address",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's street address.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "hash_recipient_street_address",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                (
                    "recipient_suburb",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's suburb or neighborhood.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "recipient_city",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's city.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "recipient_state",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's state, province, or region.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "recipient_postcode",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's postal code.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "recipient_country",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's country.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes to provide more context about the plan.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_colors",
                    models.ManyToManyField(
                        blank=True, related_name="preferred_plans", to="events.color"
                    ),
                ),
                (
                    "rejected_colors",
                    models.ManyToManyField(
                        blank=True, related_name="rejected_plans", to="events.color"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
