# Generated by Django 6.0.1 on 2026-01-28 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "hex_code",
                    models.CharField(
                        blank=True, help_text="e.g., #FFFFFF", max_length=7
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The unique discount code.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "florist_name",
                    models.CharField(
                        help_text="The name of the florist associated with this discount.",
                        max_length=100,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the discount code is currently active.",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the discount code was created.",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time the discount code expires (optional).",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        help_text="The date the flower delivery will occur."
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Custom message for this specific delivery.",
                        null=True,
                    ),
                ),
                (
                    "bouquet_preference",
                    models.CharField(
                        blank=True,
                        help_text="User's preference for the bouquet (e.g., 'Sunflowers').",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        help_text="The status of the delivery.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["delivery_date"],
            },
        ),
        migrations.CreateModel(
            name="FlowerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="pending_payment",
                        help_text="The current status of the order.",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="The three-letter ISO currency code.",
                        max_length=3,
                    ),
                ),
                (
                    "recipient_first_name",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's first name.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "hash_recipient_first_name",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                (
                    "recipient_last_name",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's last name.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "hash_recipient_last_name",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                (
                    "recipient_street_address",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's street address.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "hash_recipient_street_address",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                (
                    "recipient_suburb",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's suburb or neighborhood.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "recipient_city",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's city.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "recipient_state",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's state, province, or region.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "recipient_postcode",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's postal code.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "recipient_country",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's country.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes to provide more context about the order.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_colors",
                    models.ManyToManyField(
                        blank=True, related_name="preferred_orders", to="events.color"
                    ),
                ),
                (
                    "preferred_flower_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preferred_orders",
                        to="events.flowertype",
                    ),
                ),
                (
                    "rejected_colors",
                    models.ManyToManyField(
                        blank=True, related_name="rejected_orders", to="events.color"
                    ),
                ),
                (
                    "rejected_flower_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rejected_orders",
                        to="events.flowertype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UpfrontPlan",
            fields=[
                (
                    "orderbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.orderbase",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="The date of the first delivery.",
                        null=True,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The budget per bouquet.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "deliveries_per_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How many deliveries are scheduled per year.",
                        null=True,
                    ),
                ),
                (
                    "years",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The total number of years for the plan.",
                        null=True,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The final total amount for the plan.",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Upfront Plan",
                "verbose_name_plural": "Upfront Plans",
            },
            bases=("events.orderbase",),
        ),
    ]
