# Generated by Django 6.0.1 on 2026-01-25 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flowerplan",
            name="user",
            field=models.ForeignKey(
                help_text="The user who owns this plan.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flower_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="flower_plan",
            field=models.ForeignKey(
                help_text="The flower plan this event belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="events.flowerplan",
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="preferred_flower_types",
            field=models.ManyToManyField(
                blank=True, related_name="preferred_plans", to="events.flowertype"
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="rejected_flower_types",
            field=models.ManyToManyField(
                blank=True, related_name="rejected_plans", to="events.flowertype"
            ),
        ),
    ]
