# Generated by Django 6.0.1 on 2026-01-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowerplan",
            name="budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The budget per bouquet.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flowerplan",
            name="currency",
            field=models.CharField(
                blank=True,
                help_text="The three-letter ISO currency code.",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flowerplan",
            name="deliveries_per_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How many deliveries are scheduled per year.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flowerplan",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The final total amount for the plan.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flowerplan",
            name="years",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The total number of years for the plan.",
                null=True,
            ),
        ),
    ]
