# Generated by Django 6.0.1 on 2026-01-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_flowerplan_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowerplan",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="The date of the first delivery.", null=True
            ),
        ),
    ]
