# Generated by Django 6.0.1 on 2026-01-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_remove_flowerplan_recipient_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowerplan",
            name="hash_recipient_first_name",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="hash_recipient_last_name",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="hash_recipient_street_address",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True
            ),
        ),
    ]
