# Generated by Django 6.0.1 on 2026-01-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_notification_status"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="events_noti_status_d87fcf_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="events_noti_message_021c14_idx",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
